package com.poulstar.blocky.core;

public enum BlockTypes {
    APARTMENT_BLOCK,
    EMERGENCY_BLOCK,
    FACTORY_BLOCK,
    FIRE_STATION_BLOCK,
    HOSPITAL_BLOCK,
    HOUSE_BLOCK,
    IT_COMPANY_BLOCK,
    MALL_BLOCK,
    POLICE_STATION_BLOCK,
    SCHOOL_BLOCK,
    UNIVERSITY_BLOCK
}